package d021248.group.demo.archive;

import d021248.group.GroupFactory;
import d021248.group.cyclic.CyclicElement;
import d021248.group.cyclic.CyclicGroup;
import d021248.group.dihedral.DihedralElement;
import d021248.group.dihedral.DihedralGroup;
import d021248.group.subgroup.SpecialSubgroups;
import d021248.group.subgroup.Subgroup;
import d021248.group.symmetric.Permutation;
import d021248.group.symmetric.SymmetricGroup;
import d021248.group.util.Constants;

/**
 * Demonstrates group properties: center, commutator subgroup, isAbelian,
 * exponent.
 */
public final class GroupPropertiesDemo {
    private static final String TRIVIAL = " (trivial)";

    private GroupPropertiesDemo() {
    }

    public static void main(String[] args) {
        System.out.println(Constants.SEPARATOR_60);
        System.out.println("Group Properties Demo");
        System.out.println(Constants.SEPARATOR_60);

        demonstrateCenter();
        System.out.println();
        demonstrateCommutatorSubgroup();
        System.out.println();
        demonstrateAbelianProperty();
        System.out.println();
        demonstrateExponent();
    }

    private static void demonstrateCenter() {
        System.out.println("--- Center Z(G) ---");
        System.out.println("(Elements that commute with all group elements)");

        // Abelian group - center is the whole group
        CyclicGroup z6 = GroupFactory.cyclic(6);
        Subgroup<CyclicElement> centerZ6 = SpecialSubgroups.center(z6);
        System.out.println("\nZ_6 (abelian):");
        System.out.println("  Z(Z_6) order: " + centerZ6.order() + " (equals |G| = 6)");
        System.out.println("  For abelian groups: Z(G) = G");

        // Non-abelian symmetric group
        SymmetricGroup s3 = GroupFactory.symmetric(3);
        Subgroup<Permutation> centerS3 = SpecialSubgroups.center(s3);
        System.out.println("\nS_3 (non-abelian):");
        System.out.println("  S_3 order: " + s3.order());
        System.out.println("  Z(S_3) order: " + centerS3.order() + TRIVIAL);
        System.out.println("  Elements: " + centerS3.elements());

        // Dihedral group D_4
        DihedralGroup d4 = GroupFactory.dihedral(4);
        Subgroup<DihedralElement> centerD4 = SpecialSubgroups.center(d4);
        System.out.println("\nD_4 (symmetries of square):");
        System.out.println("  D_4 order: " + d4.order());
        System.out.println("  Z(D_4) order: " + centerD4.order());
        System.out.println("  Center contains identity and 180° rotation");
    }

    private static void demonstrateCommutatorSubgroup() {
        System.out.println("--- Commutator Subgroup [G,G] ---");
        System.out.println("(Generated by all commutators [g,h] = g⁻¹h⁻¹gh)");

        // Abelian group
        CyclicGroup z12 = GroupFactory.cyclic(12);
        Subgroup<CyclicElement> commZ12 = SpecialSubgroups.commutatorSubgroup(z12);
        System.out.println("\nZ_12 (abelian):");
        System.out.println("  [Z_12, Z_12] order: " + commZ12.order() + TRIVIAL);
        System.out.println("  For abelian groups: [G,G] = {e}");

        // Symmetric group S_3
        SymmetricGroup s3 = GroupFactory.symmetric(3);
        Subgroup<Permutation> commS3 = SpecialSubgroups.commutatorSubgroup(s3);
        System.out.println("\nS_3:");
        System.out.println("  S_3 order: " + s3.order());
        System.out.println("  [S_3, S_3] order: " + commS3.order());
        System.out.println("  [S_3, S_3] = A_3 (alternating group)");
        System.out.println("  G/[G,G] ≅ Z_2 (abelianization)");

        // Symmetric group S_4
        SymmetricGroup s4 = GroupFactory.symmetric(4);
        Subgroup<Permutation> commS4 = SpecialSubgroups.commutatorSubgroup(s4);
        System.out.println("\nS_4:");
        System.out.println("  S_4 order: " + s4.order());
        System.out.println("  [S_4, S_4] order: " + commS4.order());
        System.out.println("  [S_4, S_4] = A_4 (alternating group)");

        // Dihedral group
        DihedralGroup d3 = GroupFactory.dihedral(3);
        Subgroup<DihedralElement> commD3 = SpecialSubgroups.commutatorSubgroup(d3);
        System.out.println("\nD_3:");
        System.out.println("  D_3 order: " + d3.order());
        System.out.println("  [D_3, D_3] order: " + commD3.order());
        System.out.println("  [D_3, D_3] is the rotation subgroup");
    }

    private static void demonstrateAbelianProperty() {
        System.out.println("--- Abelian Property ---");
        System.out.println("(Does ab = ba for all elements?)");

        System.out.println("\nCyclic groups (always abelian):");
        System.out.println("  Z_6 is abelian? " + GroupFactory.cyclic(6).isAbelian());
        System.out.println("  Z_12 is abelian? " + GroupFactory.cyclic(12).isAbelian());

        System.out.println("\nSymmetric groups:");
        System.out.println("  S_1 is abelian? " + GroupFactory.symmetric(1).isAbelian() + TRIVIAL);
        System.out.println("  S_2 is abelian? " + GroupFactory.symmetric(2).isAbelian() + " (order 2)");
        System.out.println("  S_3 is abelian? " + GroupFactory.symmetric(3).isAbelian() + " (non-abelian for n≥3)");
        System.out.println("  S_4 is abelian? " + GroupFactory.symmetric(4).isAbelian());

        System.out.println("\nDihedral groups:");
        System.out.println("  D_2 is abelian? " + GroupFactory.dihedral(2).isAbelian() + " (Klein 4-group)");
        System.out.println("  D_3 is abelian? " + GroupFactory.dihedral(3).isAbelian() + " (non-abelian for n≥3)");
        System.out.println("  D_4 is abelian? " + GroupFactory.dihedral(4).isAbelian());

        System.out.println("\nDirect products:");
        var z2xz3 = GroupFactory.directProduct(GroupFactory.cyclic(2), GroupFactory.cyclic(3));
        System.out.println("  Z_2 × Z_3 is abelian? " + z2xz3.isAbelian() + " (product of abelian groups)");
    }

    private static void demonstrateExponent() {
        System.out.println("--- Exponent of Group ---");
        System.out.println("(Smallest n such that g^n = e for all g)");

        System.out.println("\nCyclic groups (exponent = order):");
        System.out.println("  Z_6: exponent = " + GroupFactory.cyclic(6).exponent() + ", order = 6");
        System.out.println("  Z_12: exponent = " + GroupFactory.cyclic(12).exponent() + ", order = 12");

        System.out.println("\nDirect products:");
        var z2xz2 = GroupFactory.directProduct(GroupFactory.cyclic(2), GroupFactory.cyclic(2));
        System.out.println("  Z_2 × Z_2 (Klein): exponent = " + z2xz2.exponent() + " (all non-identity have order 2)");

        var z2xz3 = GroupFactory.directProduct(GroupFactory.cyclic(2), GroupFactory.cyclic(3));
        System.out.println("  Z_2 × Z_3: exponent = " + z2xz3.exponent() + " = lcm(2,3)");

        var z2xz4 = GroupFactory.directProduct(GroupFactory.cyclic(2), GroupFactory.cyclic(4));
        System.out.println("  Z_2 × Z_4: exponent = " + z2xz4.exponent() + " = lcm(2,4)");

        System.out.println("\nNon-abelian groups:");
        SymmetricGroup s3 = GroupFactory.symmetric(3);
        System.out.println("  S_3: exponent = " + s3.exponent() + " = lcm(1,2,3), order = 6");

        DihedralGroup d3 = GroupFactory.dihedral(3);
        System.out.println("  D_3: exponent = " + d3.exponent() + " = lcm(1,2,3), order = 6");

        DihedralGroup d4 = GroupFactory.dihedral(4);
        System.out.println("  D_4: exponent = " + d4.exponent() + ", order = 8");

        System.out.println("\nNote: exponent always divides order");
    }
}
