package d021248.group.base;

import java.util.Collections;
import java.util.Set;

import d021248.group.Generator;
import d021248.group.Group;
import d021248.group.api.Element;
import d021248.group.api.Operation;

/**
 * Base implementation of a finite group generated by a set of elements under a
 * provided operation.
 * The closure of the generators (including identity and inverses) is computed
 * eagerly.
 */
public abstract class AbstractGroup<E extends Element> implements Group<E> {
    private final Set<E> elements;
    private final Operation<E> operation;

    protected AbstractGroup(Set<E> generators, Operation<E> operation) {
        this.operation = operation;
        this.elements = Collections.unmodifiableSet(Generator.generate(this.asGroup(operation), generators));
    }

    // Helper to allow using Generator before elements initialized.
    private Group<E> asGroup(Operation<E> op) {
        return new Group<>() {
            @Override
            public Set<E> elements() {
                return elements;
            }

            @Override
            public Operation<E> operation() {
                return op;
            }

            @Override
            public E identity() {
                return computeIdentity();
            }

            @Override
            public E inverse(E e) {
                return computeInverse(e);
            }
        };
    }

    @Override
    public Set<E> elements() {
        return elements;
    }

    @Override
    public Operation<E> operation() {
        return operation;
    }

    @Override
    public E identity() {
        return computeIdentity();
    }

    @Override
    public E inverse(E e) {
        return computeInverse(e);
    }

    /** Provide the identity element of the group. */
    protected abstract E computeIdentity();

    /** Provide the inverse of the given element. */
    protected abstract E computeInverse(E e);
}
