package d021248.group.viz;

import d021248.group.GroupFactory;
import d021248.group.cyclic.CyclicGroup;
import d021248.group.dihedral.DihedralGroup;
import d021248.group.symmetric.SymmetricGroup;
import d021248.group.util.Constants;
import d021248.group.util.ThreadUtil;

/**
 * Example methods demonstrating visualization usage patterns.
 * <p>
 * These methods show how to use the three visualization tools
 * (CayleyTableViewer, SubgroupLatticeViewer, CayleyGraphViewer)
 * with different groups and scenarios.
 * </p>
 * 
 * <p>
 * Usage from code:
 * </p>
 * 
 * <pre>
 * // Show all 3 visualizations for Z_8
 * VisualizationExamples.cyclicGroupExample();
 * 
 * // Compare abelian vs non-abelian groups
 * VisualizationExamples.comparisonExample();
 * </pre>
 */
public final class VisualizationExamples {

    private VisualizationExamples() {
    }

    /**
     * Example: Cyclic group Z_8
     * <p>
     * Shows simple cyclic structure where all subgroups form a chain.
     * </p>
     */
    public static void cyclicGroupExample() {
        System.out.println("Example 1: Cyclic Group Z_8");
        CyclicGroup z8 = GroupFactory.cyclic(8);

        CayleyTableViewer.show(z8, "Z_8 - Cayley Table");
        delay();
        SubgroupLatticeViewer.show(z8, "Z_8 - Subgroup Lattice");
        delay();
        CayleyGraphViewer.show(z8, "Z_8 - Cayley Graph");
    }

    /**
     * Example: Dihedral group D_4
     * <p>
     * Shows Klein four-group as subgroup and non-abelian structure.
     * </p>
     */
    public static void dihedralGroupExample() {
        System.out.println("\nExample 2: Dihedral Group D_4");
        DihedralGroup d4 = GroupFactory.dihedral(4);

        CayleyTableViewer.show(d4, "D_4 - Cayley Table");
        delay();
        SubgroupLatticeViewer.show(d4, "D_4 - Subgroup Lattice");
        delay();
        CayleyGraphViewer.show(d4, "D_4 - Cayley Graph");
    }

    /**
     * Example: Symmetric group S_4
     * <p>
     * Shows rich subgroup structure with 30 subgroups including A_4.
     * Warning: Large lattice visualization!
     * </p>
     */
    public static void symmetricGroupExample() {
        System.out.println("\nExample 3: Symmetric Group S_4");
        SymmetricGroup s4 = GroupFactory.symmetric(4);

        System.out.println("S_4 has order " + s4.order() + " and is non-abelian");
        System.out.println("Warning: Large lattice with 30 subgroups!");

        CayleyTableViewer.show(s4, "S_4 - Cayley Table");
        delay();
        SubgroupLatticeViewer.show(s4, "S_4 - Subgroup Lattice");
        delay();
        CayleyGraphViewer.show(s4, "S_4 - Cayley Graph");
    }

    /**
     * Example: Comparison of Z_6 (abelian) vs D_3 (non-abelian)
     * <p>
     * Both groups have order 6 but completely different structures.
     * Demonstrates how group properties affect visualizations.
     * </p>
     */
    public static void comparisonExample() {
        System.out.println("\nExample 4: Z_6 vs D_3 (both order 6)");

        var z6 = GroupFactory.cyclic(6);
        var d3 = GroupFactory.dihedral(3);

        System.out.println("Z_6: Abelian, cyclic");
        CayleyTableViewer.show(z6, "Z_6 - Cayley Table (Abelian)");
        delay();

        System.out.println("D_3: Non-abelian, isomorphic to S_3");
        CayleyTableViewer.show(d3, "D_3 ≅ S_3 - Cayley Table (Non-abelian)");
        delay();

        SubgroupLatticeViewer.show(z6, "Z_6 - Subgroup Lattice");
        delay();
        SubgroupLatticeViewer.show(d3, "D_3 - Subgroup Lattice");
    }

    /**
     * Example: Cayley graph for exploring generators
     * <p>
     * Shows D_5 with focus on generator structure.
     * Click elements to highlight generator paths.
     * </p>
     */
    public static void cayleyGraphFocus() {
        System.out.println("\nExample 5: Cayley Graph Focus");

        var d5 = GroupFactory.dihedral(5);
        System.out.println("D_5: Generated by rotation and reflection");
        System.out.println("Click elements to highlight generator paths!");

        CayleyGraphViewer.show(d5, "D_5 - Cayley Graph (Interactive)");
    }

    /**
     * Example: Subgroup lattice showing divisor structure
     * <p>
     * Z_12 lattice clearly shows how subgroups correspond to divisors of 12.
     * </p>
     */
    public static void latticeFocus() {
        System.out.println("\nExample 6: Subgroup Lattice Focus");

        var z12 = GroupFactory.cyclic(12);
        System.out.println("Z_12: Lattice shows divisors of 12");
        System.out.println("Subgroups: {e}, Z_2, Z_3, Z_4, Z_6, Z_12");

        SubgroupLatticeViewer.show(z12, "Z_12 - Divisor Lattice");
    }

    /**
     * Run all examples sequentially with delays between them.
     */
    public static void runAllExamples() {
        cyclicGroupExample();
        delay(1000);
        dihedralGroupExample();
        delay(1000);
        symmetricGroupExample();
        delay(1000);
        comparisonExample();
        delay(1000);
        cayleyGraphFocus();
        ThreadUtil.sleep(1000);
        latticeFocus();
    }

    private static void delay() {
        ThreadUtil.sleep(Constants.DEFAULT_SLEEP_MS);
    }

    private static void delay(int ms) {
        ThreadUtil.sleep(ms);
    }
}
