package d021248.group.viz.examples;

import d021248.group.GroupFactory;
import d021248.group.cyclic.CyclicGroup;
import d021248.group.dihedral.DihedralGroup;
import d021248.group.symmetric.SymmetricGroup;
import d021248.group.viz.CayleyGraphViewer;
import d021248.group.viz.CayleyTableViewer;
import d021248.group.viz.SubgroupLatticeViewer;

/**
 * Comprehensive examples demonstrating all three visualizations
 * with different groups.
 */
public final class VisualizationExamples {

    private VisualizationExamples() {
    }

    /**
     * Example 1: Cyclic group Z_8
     * Shows: Simple cyclic structure, all subgroups form a chain
     */
    public static void cyclicGroupExample() {
        System.out.println("Example 1: Cyclic Group Z_8");
        CyclicGroup z8 = GroupFactory.cyclic(8);

        CayleyTableViewer.show(z8, "Z_8 - Cayley Table");
        delay();
        SubgroupLatticeViewer.show(z8, "Z_8 - Subgroup Lattice");
        delay();
        CayleyGraphViewer.show(z8, "Z_8 - Cayley Graph");
    }

    /**
     * Example 2: Dihedral group D_4
     * Shows: Klein four-group as subgroup, non-abelian structure
     */
    public static void dihedralGroupExample() {
        System.out.println("\nExample 2: Dihedral Group D_4");
        DihedralGroup d4 = GroupFactory.dihedral(4);

        CayleyTableViewer.show(d4, "D_4 - Cayley Table");
        delay();
        SubgroupLatticeViewer.show(d4, "D_4 - Subgroup Lattice");
        delay();
        CayleyGraphViewer.show(d4, "D_4 - Cayley Graph");
    }

    /**
     * Example 3: Symmetric group S_4
     * Shows: Rich subgroup structure, 30 subgroups including A_4
     */
    public static void symmetricGroupExample() {
        System.out.println("\nExample 3: Symmetric Group S_4");
        SymmetricGroup s4 = GroupFactory.symmetric(4);

        System.out.println("S_4 has order " + s4.order() + " and is non-abelian");
        System.out.println("Warning: Large lattice with 30 subgroups!");

        CayleyTableViewer.show(s4, "S_4 - Cayley Table");
        delay();
        SubgroupLatticeViewer.show(s4, "S_4 - Subgroup Lattice");
        delay();
        CayleyGraphViewer.show(s4, "S_4 - Cayley Graph");
    }

    /**
     * Example 4: Comparison of Z_6 (abelian) vs D_3 (non-abelian)
     * Both have order 6 but different structures
     */
    public static void comparisonExample() {
        System.out.println("\nExample 4: Z_6 vs D_3 (both order 6)");

        var z6 = GroupFactory.cyclic(6);
        var d3 = GroupFactory.dihedral(3);

        System.out.println("Z_6: Abelian, cyclic");
        CayleyTableViewer.show(z6, "Z_6 - Cayley Table (Abelian)");
        delay();

        System.out.println("D_3: Non-abelian, isomorphic to S_3");
        CayleyTableViewer.show(d3, "D_3 ≅ S_3 - Cayley Table (Non-abelian)");
        delay();

        SubgroupLatticeViewer.show(z6, "Z_6 - Subgroup Lattice");
        delay();
        SubgroupLatticeViewer.show(d3, "D_3 - Subgroup Lattice");
    }

    /**
     * Example 5: Just Cayley Graph for exploring generators
     */
    public static void cayleyGraphFocus() {
        System.out.println("\nExample 5: Cayley Graph Focus");

        var d5 = GroupFactory.dihedral(5);
        System.out.println("D_5: Generated by rotation and reflection");
        System.out.println("Click elements to highlight generator paths!");

        CayleyGraphViewer.show(d5, "D_5 - Cayley Graph (Interactive)");
    }

    /**
     * Example 6: Lattice focus - groups with interesting subgroup structures
     */
    public static void latticeFocus() {
        System.out.println("\nExample 6: Subgroup Lattice Focus");

        var z12 = GroupFactory.cyclic(12);
        System.out.println("Z_12: Lattice shows divisors of 12");
        System.out.println("Subgroups: {e}, Z_2, Z_3, Z_4, Z_6, Z_12");

        SubgroupLatticeViewer.show(z12, "Z_12 - Divisor Lattice");
    }

    private static void delay() {
        try {
            Thread.sleep(300);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }

    /**
     * Run all examples
     */
    public static void main(String[] args) {
        if (args.length == 0) {
            printUsage();
            return;
        }

        String example = args[0].toLowerCase();

        switch (example) {
            case "1", "cyclic" -> cyclicGroupExample();
            case "2", "dihedral" -> dihedralGroupExample();
            case "3", "symmetric", "s4" -> symmetricGroupExample();
            case "4", "compare", "comparison" -> comparisonExample();
            case "5", "graph" -> cayleyGraphFocus();
            case "6", "lattice" -> latticeFocus();
            case "all" -> {
                cyclicGroupExample();
                delay(1000);
                dihedralGroupExample();
                delay(1000);
                symmetricGroupExample();
                delay(1000);
                comparisonExample();
                delay(1000);
                cayleyGraphFocus();
                delay(1000);
                latticeFocus();
            }
            default -> {
                System.out.println("Unknown example: " + example);
                printUsage();
            }
        }
    }

    private static void delay(int ms) {
        try {
            Thread.sleep(ms);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }

    private static void printUsage() {
        System.out.println("Group Visualization Examples");
        System.out.println("\nUsage: VisualizationExamples <example>");
        System.out.println("\nExamples:");
        System.out.println("  1 or cyclic     - Z_8 (simple cyclic group)");
        System.out.println("  2 or dihedral   - D_4 (contains Klein four-group)");
        System.out.println("  3 or symmetric  - S_4 (30 subgroups!)");
        System.out.println("  4 or compare    - Z_6 vs D_3 (both order 6)");
        System.out.println("  5 or graph      - D_5 Cayley graph focus");
        System.out.println("  6 or lattice    - Z_12 lattice focus");
        System.out.println("  all             - Run all examples");
        System.out.println("\nInteractive features:");
        System.out.println("  - Hover over table cells to see operations");
        System.out.println("  - Hover over lattice nodes to see details");
        System.out.println("  - Click graph nodes to highlight paths");
    }
}
